trigger:
  branches:
    include:
      - main

pool:
  name: dockerPool

steps:
- script: |
    set -e

    git config --global user.email "alexander@allroggen.nl"
    git config --global user.name "Mirror Bot"

    # Repo spiegeln (bare clone)
    git clone --mirror https://$(System.AccessToken)@dev.azure.com/licht85/LawOfWriter/_git/LawOfWriter
    cd LawOfWriter.git

    # Direkt pushen ohne Remote-Konflikte
    git push --mirror https://allroggen:$(GITHUB_PAT)@github.com/allroggen/LawOfWriter.git

  displayName: 'Mirror Azure → GitHub'